Improve Validation and Error Handling in QCNN Sequence Method
SaashaJoshi/piQture pull request #147
Opened 2024-11-09 10:26 UTC by amansingh2116

#Resolves https://github.com/SaashaJoshi/piQture/issues/42
This PR enhances the `QCNN` class's `sequence` method to include more robust validation and error handling for the list of layer operations. The changes aim to prevent incorrect or incompatible layer configurations and improve readability of error messages for users.

#### **Summary of Changes:**
- **Validation of Layers:** Ensures that each layer passed to `sequence`:
  - Is a class.
  - Inherits from `BaseLayer`.
  - Is not the abstract `BaseLayer` itself.
- **Parameter Checks:** Verifies that parameters provided for each layer are in a dictionary format.
- **Error Messages:** Improved error messages for clearer troubleshooting.
- **Test Coverage:** Added minimal unit tests to confirm valid and invalid layer inputs:
  - Test for single valid layer and multiple valid layers.
  - Test for rejection of non-layer classes, built-in functions, and invalid parameter types.

#### **Testing:**
All new and existing tests in `test_qcnn.py` pass, indicating that the `sequence` method correctly validates inputs and handles errors as expected. The `test_qcnn.py` file can be deleted after checking for the errors, it was created just for test purposes.

2024-11-29 15:32 UTC, SaashaJoshi commented
Hi @amansingh2116, Thanks for the PR. I will get back to this asap.

2024-12-03 09:44 UTC, amansingh2116 commented
Is there something that I should change or some error while merging the PR?

2024-12-11 16:09 UTC, SaashaJoshi commented
Hi @amansingh2116,
The unit tests and linting tests seem to fail for the current code. Can you run `tox -e lint` to see where you can make changes? Let me know if you will need more help here.

2024-12-11 16:20 UTC, SaashaJoshi commented
Also, the unit tests are failing because there already exists a `test_qcnn.py` file in the `tests` directory. You will have to merge your code from the test file to the existing `test_qcnn.py` file in order for the github actions to trigger the correct tests.

2024-12-20 18:42 UTC, amansingh2116 commented on piqture/neural_networks/qcnn.py
> +        return self.circuit
Hi! @SaashaJoshi , I’ve addressed the comments about `test_qcnn.py` & linting issues and updated the error handling logic. Please review the latest changes.

2024-12-31 16:37 UTC, amansingh2116 commented
I have fixed the linting issues and merged the test cases in the original `test_qcnn.py` file. Please let me know if I should change something else too to merge the PR. @SaashaJoshi

2025-01-02 17:13 UTC, SaashaJoshi requested changes
Hey,

The unit tests look very nice now. I am suggested a few changes, mostly dealing with how we can match error messages by utilizing a regex expression in the `raises` class. Thanks for your hard work, really appreciated!

2025-01-02 17:13 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
>      def test_operation(self, num_qubits, operations):
```suggestion
    def test_operation_isclass(self, num_qubits, operations):
```

2025-01-02 17:13 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +            _ = QCNN(num_qubits).sequence(operations)
We are already checking if the operation is a class in the `test_operation` function. You can add the new test cases to the parameterizations in the above function.

2025-01-02 17:13 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +    def test_non_baselayer_operations(self, num_qubits, operations):
The keyword `operations` refers to the entire dictionary containing various operation/layers. I am renaming the function to `test_non_baselayer_operation`

```suggestion
    def test_non_baselayer_operation(self, num_qubits, operations):
```

2025-01-02 17:13 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +            (4, [(object, {})]),
You can also add parameterizations with other classes from inside the library such as as, `MERA`, `QCNN`, etc. to verify if the test case catches them as well.

2025-01-02 17:13 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +        with raises(TypeError, match="must inherit from BaseLayer"):
The match argument must contain the exact error message that we are looking for. Use regex here as well.

```suggestion
        with raises(TypeError, match=r"Operation at index \d+\ must inherit from BaseLayer, got \*?"):
```

2025-01-02 17:13 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +    def test_baselayer_itself(self, num_qubits, operations):
```suggestion
    def test_baselayer(self, num_qubits, operations):
```

2025-01-02 17:13 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +        with raises(TypeError, match="cannot be BaseLayer itself"):
The match argument must be corrected here as well.

2025-01-13 04:02 UTC, amansingh2116 commented
I have fixed the Regex pattern matching issue. Please take a look @SaashaJoshi to review the Pull Request.

2025-01-13 16:44 UTC, SaashaJoshi reviewed
Hi @amansingh2116,

Thanks for the quick changes. I made a few quick suggestions, apart from that everything lgtm!

2025-01-13 16:44 UTC, SaashaJoshi commented on piqture/neural_networks/qcnn.py
> +                    f"Operation at index {idx} cannot be BaseLayer itself, got *"
What does the asterisk denote here? We can simply have:
```suggestion
                    f"Operation at index {idx} cannot be BaseLayer itself."
```

2025-01-13 16:44 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +            match=r"Operation at index \d+\ cannot be BaseLayer itself, got \*?",
Making corresponding changes here.
```suggestion
            match=r"Operation at index \d+\ cannot be BaseLayer itself.",
```

2025-01-13 16:44 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +        """Tests that classes not inheriting from BaseLayer are rejected."""
```suggestion
        """Tests if the layer operation inherits from the abstract BaseLayer class."""
```

2025-01-13 16:44 UTC, SaashaJoshi commented on tests/neural_networks/test_qcnn.py
> +        """Tests that BaseLayer itself is rejected."""
```suggestion
        """Tests if the layer operation is the abstract BaseLayer class."""
```

2025-01-13 22:07 UTC, amansingh2116 commented
Done @SaashaJoshi! Thanks for the guidance.

2025-01-13 22:26 UTC, SaashaJoshi commented
Thanks for the contribution, @amansingh2116 !

2025-01-13 22:26 UTC, merged